# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Server
source:           docs
destination:      _gh_pages
encoding:         UTF-8


layouts_dir:     _layouts
includes_dir:    _includes